### PR TITLE
Gatsby v3

### PR DESCRIPTION
**Pull request by axe312ger**
* [x] migrate to gatsby v3
* [x] migrate to webpack 5
* [x] replace gatsby-image with gatsby-plugin-image
* [x] migrate to emotion v11
* [x] migrate to tailwind v2
* [x] migrate to twin.macro v2
* [x] fix issues with gatsby-plugin-sitemap

## details

* build: upgrade dependencies to Gatsby v3
* fix: adjust webpack config to build in v3
* remove no more existing FAST_REFRESH flag
* fix schema adjustments
* refactor(images): use new gatsby-plugin-image to render images
* refactor(images): image rendering is now part of the theme, used by MDX components
* feat(images): add original image height and width to media context
* perf(images): use FULL_WIDTH layout from gatsby-plugin-image

## todo

* [x] remove all gatsby-image leftovers
* [x] clean up dependencies
* [x] animations seem to be broken
* [x] webpack size plugin is broken

```
 ERROR

Error: Content and Map of this Source is not available (only size() is supported)
    at SizeOnlySource._error (/Users/bene/dev/projects/gatsby-mdx-suite/node_modules/webpack/node_modules/webpack-sources/lib/SizeOnlySource.js:16:10)
    at SizeOnlySource.source (/Users/bene/dev/projects/gatsby-mdx-suite/node_modules/webpack/node_modules/webpack-sources/lib/SizeOnlySource.js:26:14)
    at /Users/bene/dev/projects/gatsby-mdx-suite/node_modules/size-plugin/dist/size-plugin.cjs:2989:96
    at Array.map (<anonymous>)
    at SizePlugin.outputSizes (/Users/bene/dev/projects/gatsby-mdx-suite/node_modules/size-plugin/dist/size-plugin.cjs:2989:48)

```

### CODE REVIEW

**Comment by zbynek** [comment]
@axe312ger the problem with sitemap is that misspelled options fail with unrelated error message, in your case `exclude` should be `excludes` (see https://github.com/gatsbyjs/gatsby/issues/31342)

**Comment by axe312ger** [comment]
@zbynek ohh thx, I'll have a look!

**Comment by axe312ger** [comment]
@zbynek thanks! That was it! :)

**Comment by axe312ger** [comment]
still having issues, will create a PR with a minimal v3 upgrade now. No emotion n stuff.

**Pull request closed without merging**
